# Generated by Django 5.1.2 on 2024-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0002_convidados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidados',
            name='token',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
