# Generated by Django 5.1.2 on 2024-11-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_alter_convidados_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentes',
            old_name='reservar',
            new_name='reservado',
        ),
        migrations.AddField(
            model_name='presentes',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noivos.convidados'),
        ),
    ]
