# Generated by Django 5.1.2 on 2024-11-02 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_presente', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='presentes/')),
                ('importancia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Convidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('presente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='convidados.presentes')),
            ],
        ),
    ]
